name = "cubercsl-api"
main = "src/index.ts"
compatibility_date = "2023-05-14"
usage_model = "bundled"

analytics_engine_datasets = [
    { binding = "CUBERCSL_API" }
]

[env.production.vars]
ENVIRONMENT = "production"
