name = "cubercsl-api"
main = "src/index.ts"
compatibility_date = "2023-05-14"

analytics_engine_datasets = [
    { binding = "CUBERCSL_API" }
]

[vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"
